### ISSUE TITLE
Cursorline and terminal color

### ISSUE THREAD

**Issue by kristijanhusak** [habamax/vim-polar#2]
Hi,

Is there a chance to add a simple way to change cursorline color (and all related things to it, like CursorLineNr, CursorColumn, etc.)? It's a bit too gray, and creates a lot of contrast.

Also, I noticed that terminal colors are not right. When I run color test, I get black as white and white as black. This causes some issues in other TUI applications (like lazygit). Here's the screenshot:
![screenshot](https://i.imgur.com/S9R4xAG.png)

**Comment by habamax** [comment]
Sure, could you propose colors? Both for cursorline(and friends) and TUI

**Comment by kristijanhusak** [comment]
For TUI, I think you just need to switch some variables, since black shows as white, and vice versa.
For cursorline color, maybe `#F4F4F4` would be ok.

**Comment by habamax** [comment]
pls check latest -- for TUI I have only changed white <-> black. Would update more If you give me more input

**Comment by kristijanhusak** [comment]
TUI is fixed, thanks!
CursorLine is also fixed, but I would like to have same color for the ColorColumn.

**Comment by habamax** [comment]
> but I would like to have same color for the ColorColumn.

which one?

**Comment by kristijanhusak** [comment]
Same as CursorLine, `#F4F4F4`.

**Comment by habamax** [comment]
> 
> 
> Same as CursorLine, `#F4F4F4`.

done

**Comment by kristijanhusak** [comment]
Looks good, thanks!

**Comment by kristijanhusak** [comment]
@habamax sorry to bother, but I think we changed too much hl groups with this. QuickfixLine should have an old color, since it's hardly distinguishable when quickfix list is opened and you go through it.

**Comment by habamax** [comment]
Pls check master

**Comment by kristijanhusak** [comment]
Thanks!
