### ISSUE TITLE
Git diff colors

### ISSUE THREAD

**Issue by kristijanhusak** [habamax/vim-polar#3]
I noticed while using [fugitive](https://github.com/tpope/vim-fugitive) that diff colors in fugitive buffer are different from diff colors used in vim diff. It shows blue for added, and gray for deleted.
I think it should be red and green.
Fugitive uses git filetype, which uses `diffAdded` and `diffRemoved` hl groups to show added/removed lines.
I guess using green like it is used for strings, and red that is used for error msg will be ok.

**Comment by habamax** [comment]
done.

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by habamax** [comment]
I would also change fugitiveHunk (reddish now) and probably fugitive header, not sure tbh.
